# Generated by Django 2.1.4 on 2019-02-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='user',
        ),
    ]
