# Generated by Django 2.1.4 on 2019-02-12 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_question', '0002_remove_testquestion_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='testquestion',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 30)),
        ),
    ]
