# Generated by Django 2.1.4 on 2019-02-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_question', '0003_auto_20190212_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='is_reading',
            field=models.BooleanField(default=False),
        ),
    ]
