# Generated by Django 2.1.4 on 2019-02-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_question', '0004_testquestion_is_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
