# Generated by Django 2.1.4 on 2019-02-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_question', '0007_auto_20190219_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestion',
            name='is_reading',
        ),
    ]
