# Generated by Django 2.1.4 on 2019-02-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_question', '0008_remove_testquestion_is_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='is_reading',
            field=models.BooleanField(default=False),
        ),
    ]
