# Generated by Django 2.1.4 on 2019-02-19 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_question', '0009_testquestion_is_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtest',
            name='time_recommended',
            field=models.DurationField(default=datetime.timedelta(0, 1200)),
        ),
    ]
