# Generated by Django 2.1.4 on 2019-02-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_question', '0010_readingtest_time_recommended'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadingTest',
        ),
    ]
