# Generated by Django 2.2.2 on 2019-06-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_answer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='time_started',
        ),
    ]
