# Generated by Django 2.1.7 on 2019-02-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_answer', '0003_auto_20190219_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='number',
            field=models.IntegerField(default=-1),
        ),
    ]
