# Generated by Django 2.1.4 on 2019-02-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_answer', '0004_studentanswer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='started',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='time_started',
            field=models.TimeField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
