# Generated by Django 2.1.4 on 2019-02-19 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_answer', '0006_auto_20190219_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='time_started',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
