# Generated by Django 2.1.4 on 2019-02-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_answer', '0009_auto_20190219_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='started',
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='time_started',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
