# Generated by Django 2.1.4 on 2019-02-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_answer', '0010_auto_20190219_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='time_started',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
