# Generated by Django 2.1.4 on 2019-02-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_answer', '0012_auto_20190219_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='time_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
