# Generated by Django 2.1.7 on 2019-03-04 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(default=0)),
                ('amount_stud', models.SmallIntegerField(default=0)),
                ('avg_time', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
    ]
