# Generated by Django 2.2.2 on 2019-06-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='avg_time',
            field=models.FloatField(default=7),
        ),
    ]
