# Generated by Django 2.1.7 on 2019-03-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20190304_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amount_teach',
            field=models.SmallIntegerField(default=0),
        ),
    ]
