# Generated by Django 2.1.7 on 2019-03-05 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_amount_teach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='avg_time',
            field=models.DurationField(default=datetime.timedelta(0, 420)),
        ),
    ]
