# Generated by Django 2.2.1 on 2019-06-01 23:37

from django.db import migrations, models
import evaluation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scaler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower', models.SmallIntegerField()),
                ('upper', models.SmallIntegerField()),
                ('level', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Pre-Intermediate'), ('B2', 'Intermediate'), ('C1', 'Upper-Intermediate'), ('C2', 'Advanced')], default=evaluation.models.TestLevel('Beginner'), max_length=29)),
            ],
        ),
    ]
