# Generated by Django 2.2.1 on 2019-05-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_examsession_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='start_button',
            field=models.BooleanField(default=False),
        ),
    ]
