# Generated by Django 2.1.7 on 2019-03-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speaking_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherspeaking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.Room'),
        ),
    ]
