# Generated by Django 2.1.4 on 2019-02-20 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time_recommended', models.DurationField(default=datetime.timedelta(0, 1200))),
            ],
        ),
    ]
