# Generated by Django 2.1.4 on 2019-02-04 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_pref.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_preference', models.CharField(choices=[(user_pref.models.Preference('Student'), 'Student'), (user_pref.models.Preference('Teacher'), 'Teacher'), (user_pref.models.Preference('Admin'), 'Admin')], max_length=7)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
