# Generated by Django 2.1.4 on 2019-02-04 20:11

from django.db import migrations, models
import user_pref.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_pref', '0002_auto_20190204_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='user_preference',
            field=models.CharField(choices=[('Student', user_pref.models.Preference('Student')), ('Teacher', user_pref.models.Preference('Teacher')), ('Admin', user_pref.models.Preference('Admin'))], max_length=19),
        ),
    ]
