# Generated by Django 2.1.4 on 2019-02-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_pref', '0003_auto_20190204_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='user_preference',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('ADMIN', 'Admin')], default='STUDENT', max_length=19),
        ),
    ]
